import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { auth, googleAuthProvider } from './db.js';
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';

export default function App() {
  const signInWithGoogle = async () => {
    await auth.signInWithPopup(googleAuthProvider);
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Čajový deník</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <Box className="main">
        <h1>Čajový deník</h1>
        <p>
          Aplikace Čajový deník je dobrou přítelkyní každému, koho těší cesta
          čaje a rád by si své kroky zaznamenával. Na jednom místě si můžete
          ukládat oblíbené čaje a degustační zápisy. Nepřeberné čajové horizonty
          čekají na objevení.
        </p>

        <Button variant="outlined">
          <Link href="/signin">
            <a>Vytvořit účet</a>
          </Link>
        </Button>

        <p>Máte již svůj účet? Přihlaste se!</p>
        <Button variant="outlined">
          <Link href="/login">
            <a>Přihlásit se</a>
          </Link>
        </Button>
        <Button variant="outlined" onClick={signInWithGoogle}>
          Přihlásit se pomocí Google účtu
        </Button>
      </Box>
    </>
  );
}
