import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Button from '@mui/material/Button';
import logo from '../public/teapot.png';
import { Stack } from '@mui/material';
import { getProviders, signIn, signOut, useSession } from 'next-auth/react';
import React, { useEffect, useState } from 'react';
import LogoutIcon from '@mui/icons-material/Logout';
import wallpaper from '../public/wallpaper.png';

export default function App() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Čajový deník</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          />
          <script
            src="https://kit.fontawesome.com/c22e5ccbaa.js"
            crossorigin="anonymous"
          ></script>
        </Head>
      </div>
      <Stack
        className="main"
        direction="column"
        justifyContent="center"
        alignItems="center"
        spacing={3}
      >
        <Image src={logo} alt=""></Image>
        <h1>Čajový deník</h1>
        <p>
          Aplikace Čajový deník je dobrou přítelkyní každému, koho těší cesta
          čaje a rád by si své kroky zaznamenával. Na jednom místě si můžete
          ukládat oblíbené čaje a do budoucna přibudou degustační zápisy a mnoho
          dalšího. Nepřeberné čajové horizonty čekají na objevení.
        </p>

        <Link href="/login" passHref>
          <Button variant="contained">
            <a>Přihlášení</a>
          </Button>
        </Link>

        {/*<Link href="/signin" passHref>
          <Button variant="outlined">
            <a>Vytvořit účet</a>
          </Button>
        </Link>

        <p>Máte již svůj účet? Přihlaste se!</p>



        <Link href="/blog" passHref>
          <Button variant="outlined">
            <a>Blog</a>
          </Button>
        </Link>

        <Button
          variant="outlined"
          onClick={() => signOut({ callbackUrl: '/' })}
          startIcon={<LogoutIcon />}
        >
          Odhlásit
        </Button>*/}
      </Stack>
    </>
  );
}
